import classes from "./Auth.module.css";
import { actions } from "@/store";
import { useDispatch } from "react-redux";

const Auth = () => {
  const dispatch = useDispatch();
  const submitHandler = (event: React.FormEvent) => {
    event.preventDefault();
    // We don't want to send a request to the server
    // Generated by copilot and verified by lecture,
    // But IDK what that means.
    // Need to study more later
    dispatch(actions.authActions.login());
  };
  return (
    <main className={classes.auth}>
      <section>
        <form onSubmit={submitHandler}>
          <div className={classes.control}>
            <label htmlFor="email">Email</label>
            <input type="email" id="email" />
          </div>
          <div className={classes.control}>
            <label htmlFor="password">Password</label>
            <input type="password" id="password" />
          </div>
          <button>Login</button>
        </form>
      </section>
    </main>
  );
};

export default Auth;
